# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29b8ffcd4ead659b39296c9a0a55d2d9fef18cf3ca88cfc5f00108073c530218cec700cfd2c8d92818c0b8a31b01ad8394ace25f21ceb82cb62c86bdf40b9933

test:
  secret_key_base: d91d09e5b0f81bec75be336154b280771e29abbaddbe54f15b78cf86947b8a8d6fb29c12aacf5fc6a976c9312aea987e3639d50680de6d8f10b7c6ac65d1911f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
